services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app/models:/app/app/models
    environment:
      RVC_API_URL: http://rvc-service:5050
      OLLAMA_API_URL: http://ollama:11434
    depends_on:

      - ollama

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data: